### ISSUE TITLE
Unable to Remotely Debug APIM Policies with VS Code and APIM Extension 

### ISSUE THREAD

**Issue by marcami** [microsoft/vscode-apimanagement#165]
I followed the instructions at the link below to debug my APIM policies with VS Code 1.53.2 and APIM Extension 0.1.8 on Windows x64 10.0.19042, but the the APIM Extension did not automatically open a new editor window after establishing the debugging session via the "Start Policy Debugging" context menu.  So I manually opened a new editor wiindow and sent an HTTP request to my API.  Although a successful response was received, the APIM Extension did not open a debug  window showing that it had entered my policy, nor did it stop at any breakpoints.

[https://docs.microsoft.com/en-us/azure/api-management/api-management-debug-policies](url)

Previous to installing VS Code 1.53.2, this APIM policy debugging feature was working for me.   My launch.json file looks like this:

`{
    "version": "0.2.0",
    "configurations": [    
        {
            "type": "apim-policy",
            "request": "launch",
            "name": "Attach to APIM",
            "stopOnEntry": true
        }
    ]
}`

**Comment by RupengLiu** [comment]
@marcami Can I know the skuType of the instance?

**Comment by marcami** [comment]
@RupengLiu Developer

**Comment by RupengLiu** [comment]
while you are writing the HTTP Request file, did you add the Ocp-Apim-Debug header like the example below:
![image](https://user-images.githubusercontent.com/29927264/108777775-2d535400-7519-11eb-80a0-5a29c6c12094.png)

**Comment by marcami** [comment]
I added the Ocp-Apim-Debug header, and I get the Ocp-Apim-Trace-Location in my response.  However, I am not breaking on entry into my APIM policy.

**Comment by RupengLiu** [comment]
Week ago, there was an regression from the backend that breaks the debugging feature. I fixed it and reupload the vscode extension (same version) to the marketplace, can you try uninstall and install again

**Comment by marcami** [comment]
I uninstalled v0.1.8 of the APIM extension and re-installed it, but I still get the same behavior.

**Comment by marcami** [comment]
Thx!  This fixes my issue.
